create table if not exists public.notion_export_archives (
  user_id uuid primary key references auth.users(id) on delete cascade,
  root_page_id text not null,
  root_page_url text not null,
  books_data_source_id text not null,
  sentences_data_source_id text not null,
  memos_data_source_id text not null,
  created_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now()
);

create table if not exists public.notion_export_page_mappings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source_type text not null check (source_type in ('book', 'sentence', 'memo')),
  source_id bigint not null,
  notion_page_id text not null,
  notion_page_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_type, source_id)
);

create index if not exists notion_export_page_mappings_user_id_idx
  on public.notion_export_page_mappings(user_id);

alter table public.notion_export_archives enable row level security;
alter table public.notion_export_page_mappings enable row level security;

revoke all on table public.notion_export_archives from anon, authenticated;
revoke all on table public.notion_export_page_mappings from anon, authenticated;
